-- DO NOT RUN IF CATEGORIES ALREADY EXIST
-- Categories Seed
INSERT INTO categories (id, name, sort_order) VALUES 
(uuid_generate_v4(), 'ICE CREAM', 1),
(uuid_generate_v4(), 'HALF & REAL', 2),
(uuid_generate_v4(), 'PACKING', 3),
(uuid_generate_v4(), 'CADBURY', 4),
(uuid_generate_v4(), 'COLD DRINKS', 5),
(uuid_generate_v4(), 'FLAVOUR MILK', 6),
(uuid_generate_v4(), 'MILK-SHAKE', 7),
(uuid_generate_v4(), 'PARTY PACK', 8),
(uuid_generate_v4(), 'SHRIKHAND', 9),
(uuid_generate_v4(), 'TOPPING ICE', 10),
(uuid_generate_v4(), 'GINGER', 11);

-- Ice Cream Products Seed
WITH ice_cream_cat AS (SELECT id FROM categories WHERE name = 'ICE CREAM' LIMIT 1)
INSERT INTO products (category_id, name, price, sort_order) VALUES 
((SELECT id FROM ice_cream_cat), 'Savaliya Special', 0.00, 1),
((SELECT id FROM ice_cream_cat), 'American Dry Fruit', 0.00, 2),
((SELECT id FROM ice_cream_cat), 'Anjeer', 0.00, 3),
((SELECT id FROM ice_cream_cat), 'Belgian Chocolate', 0.00, 4),
((SELECT id FROM ice_cream_cat), 'Blue Diamond', 0.00, 5),
((SELECT id FROM ice_cream_cat), 'Butter Scotch', 0.00, 6),
((SELECT id FROM ice_cream_cat), 'Caramel Chocolate', 0.00, 7),
((SELECT id FROM ice_cream_cat), 'Choco Chips', 0.00, 8),
((SELECT id FROM ice_cream_cat), 'Chocolate Oriyo', 0.00, 9),
((SELECT id FROM ice_cream_cat), 'Cookies Cream', 0.00, 10),
((SELECT id FROM ice_cream_cat), 'Crunchy Munchy', 0.00, 11),
((SELECT id FROM ice_cream_cat), 'Desert Topping', 0.00, 12),
((SELECT id FROM ice_cream_cat), 'Dryfruit Khajana', 0.00, 13),
((SELECT id FROM ice_cream_cat), 'Golden Pearl', 0.00, 14),
((SELECT id FROM ice_cream_cat), 'Hira-Moti', 0.00, 15),
((SELECT id FROM ice_cream_cat), 'Hot Brownie With Vanilla', 0.00, 16),
((SELECT id FROM ice_cream_cat), 'Jambu', 0.00, 17),
((SELECT id FROM ice_cream_cat), 'Jamfal', 0.00, 18),
((SELECT id FROM ice_cream_cat), 'Japani Hungama', 0.00, 19),
((SELECT id FROM ice_cream_cat), 'Kaju Draksh', 0.00, 20),
((SELECT id FROM ice_cream_cat), 'Kesar Pista', 0.00, 21),
((SELECT id FROM ice_cream_cat), 'Lotus Biscoff', 0.00, 22),
((SELECT id FROM ice_cream_cat), 'Mango', 0.00, 23),
((SELECT id FROM ice_cream_cat), 'Mava Malai', 0.00, 24),
((SELECT id FROM ice_cream_cat), 'Mexican Khajana', 0.00, 25),
((SELECT id FROM ice_cream_cat), 'Musk Melon', 0.00, 26),
((SELECT id FROM ice_cream_cat), 'Pan Masala', 0.00, 27),
((SELECT id FROM ice_cream_cat), 'Payna Orange', 0.00, 28),
((SELECT id FROM ice_cream_cat), 'Raj Bhog', 0.00, 29),
((SELECT id FROM ice_cream_cat), 'Rajdhani', 0.00, 30),
((SELECT id FROM ice_cream_cat), 'Red Velvet', 0.00, 31),
((SELECT id FROM ice_cream_cat), 'Sitaphal', 0.00, 32),
((SELECT id FROM ice_cream_cat), 'Strawberry', 0.00, 33),
((SELECT id FROM ice_cream_cat), 'Tender Coconut', 0.00, 34),
((SELECT id FROM ice_cream_cat), 'Thandai', 0.00, 35),
((SELECT id FROM ice_cream_cat), 'Tiramisu', 0.00, 36),
((SELECT id FROM ice_cream_cat), 'Vanilla', 0.00, 37),
((SELECT id FROM ice_cream_cat), 'White House', 0.00, 38),
((SELECT id FROM ice_cream_cat), 'Wild Berry', 0.00, 39),
((SELECT id FROM ice_cream_cat), 'Winter Cream', 0.00, 40),
((SELECT id FROM ice_cream_cat), 'Baki Na', 0.00, 41),
((SELECT id FROM ice_cream_cat), 'Pop Corn', 0.00, 42);
